version: 0.0
os: linux
files:
  - source: /wordpress/
    destination: /var/www/html/
files_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: wordpress/scripts/install_dependencies.sh
      timeout: 300
      runas: root
